### ISSUE TITLE
希望增强提取mdd中图片的功能。

### ISSUE THREAD

**Issue by VimWei** [noword/MdxConverter#11]
带有图片的词典，好像大都无法正常提取：
 
1. 有部分带图片的词典（通常图片是重复且简单的），输出html是正常的，但输出pdf就看不到图片。
2. 有部分带图片的词典（通常图片较大、多个不同的图片），无论输出html还是pdf都看不到图片。

**Comment by noword** [comment]
请给出用例

**Comment by VimWei** [comment]
> 有部分带图片的词典（通常图片是重复且简单的），输出html是正常的，但输出pdf就看不到图片。

比如这个词典：链接：https://pan.baidu.com/s/1g6BW_ivxeUGYmlqQK-tViQ?pwd=3neb  提取码：3neb 

其特点是：每个例句或词头的读音图标都是重复使用几张图片。

**默认情况下，mdxconverter只能将第一次遇到的图片提取出来，而之后再次出现的都无法正确提取。如下图的方框处就是缺失的图片：**

![image](https://github.com/noword/MdxConverter/assets/25874852/302235a2-2e22-44bb-9f2c-09c46bdb4cce)


**只有我先将相关的图片都手动提取出来，并放到对应目录下，才能正确显示出来：**

![image](https://github.com/noword/MdxConverter/assets/25874852/ab3c213d-a62f-4666-bdb6-d50567abdc9f)

**Comment by VimWei** [comment]
> 有部分带图片的词典（通常图片较大、多个不同的图片），无论输出html还是pdf都看不到图片。

比如这个词典：http://pan.baidu.com/s/1_TznWWQvbQj5_833VpKoRg?pwd=x53u

我用词典软件可以正常查询出图片：

![image](https://github.com/noword/MdxConverter/assets/25874852/e6ba9665-ba15-4720-8d8b-5f2d1a228280)

**若我用mdxconverter输出html 或 pdf，则读音喇叭图片和正文图片都无法提取出来：**

![image](https://github.com/noword/MdxConverter/assets/25874852/9747e7c6-77eb-4ec0-8c4f-ef7cc032c0fb)


![image](https://github.com/noword/MdxConverter/assets/25874852/1b1af847-c706-4f6a-b71f-e88ef2af09dc)

**Comment by VimWei** [comment]
上述第一个案例，可以看到mdxconverter会提取相关的图片：

![image](https://github.com/noword/MdxConverter/assets/25874852/2f6d463d-d162-4283-bd62-b67684398def)

但第二个案例，没有看到mdxconverter提取相关的图片：

![image](https://github.com/noword/MdxConverter/assets/25874852/6d3fd806-d97b-4522-a1d6-d0e2ac9aac1f)

**Comment by VimWei** [comment]
我发现程序有4个地方需要改进：

1、对于同一个页面多次重复引用图一图片的情形，不能正确处理（原程序将重复的部分都跳过了）
2、对于非png的图片不能处理（原程序只是将png图片转为Base64 字符串了，却没有处理jpg、gif等不同的图片格式）
3、对于多种img标签的写法不兼容（原程序只支持一种）。
4、对于多mdd的词典不支持（原程序只支持一个mdd的词典）

对于前3条，可以通过修订MdxConverter的代码解决。
对于第4条，见下文讨论。

**Comment by VimWei** [comment]
此外，对于第二个案例，那是因为这个程序无法处理 多个mdd的情形，估计是因为这个程序所依赖的MdictQuery不支持对多mdd的查询。

其实，[mdict-query](https://github.com/mmjang/mdict-query) 所依赖的[readmdict](https://bitbucket.org/xwang/mdict-analysis)早就更新可以支持多mdd了，但是[mdict-query](https://github.com/mmjang/mdict-query) 并没有跟进这个特性。因此，需要[mdict-query](https://github.com/mmjang/mdict-query)进行更新。

**Comment by VimWei** [comment]
修订后的加强版  https://forum.freemdict.com/t/topic/26084
