### ISSUE TITLE
pdf打印字体大小设置

### ISSUE THREAD

**Issue by AnabasisXu** [noword/MdxConverter#4]
请教：发现打印出来的pdf字体偏小影响阅读，有没有办法设定导出的字体大小来着？是在词典的css中修改吗》
找了一圈wkhtmltopdf也没有找到怎么设置的方法。
[sample.pdf](https://github.com/noword/MdxConverter/files/5522764/sample.pdf)

**Comment by noword** [comment]
能否导出到html打印，chrome能在打印时，设置缩放

**Comment by AnabasisXu** [comment]
我一开始是这么做的，但发现wkhtmltopdf打印本地的时候，打印不完整。

[actdayin.pdf](https://github.com/noword/MdxConverter/files/5523879/actdayin.pdf)
可以看到，只打印了一半左右的html内容
